Repository storybookjs/test-runner, pull requests merged in 2022-12, with the labels that each got.

#233 Fix target url in error feedback
  src/setup-page.ts
Labels: patch, pick

#234 Fix target url in error feedback
  src/setup-page.ts
Labels: patch

#237 Updating deps to handle TS 4.9
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .storybook/is-test-runner.ts
  package.json
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/util/getStorybookMain.ts
  src/util/getStorybookMetadata.test.ts
  yarn.lock
Labels: bug, patch
