Repository storybookjs/test-runner, pull requests merged in 2022-01, with the labels that each got.

#11 MVP Prototype
  .babelrc.js
  .github/workflows/test.yml
  .gitignore
  .prettierrc
  .storybook/main.js
  README.md
  bin/test-storybook.js
  jest.config.js
  jsdom-jest.config.js
  jsdom/transform.js
  mocks/fileMock.js
  mocks/htmlMock.js
  mocks/styleMock.js
  package.json
  playwright/custom-environment.js
  playwright/global-setup.js
  playwright/global-teardown.js
  playwright/transform.js
  scripts/eject-typescript.mjs
  scripts/prepublish-checks.mjs
  src/Panel.tsx
  src/Tab.tsx
  src/Tool.tsx
  src/components/List.tsx
  src/components/PanelContent.tsx
  src/components/TabContent.tsx
  src/constants.ts
  src/csf/transformCsf.ts
  src/index.ts
  src/jsdom/index.ts
  src/jsdom/transformJsdom.test.ts
  src/jsdom/transformJsdom.ts
  src/playwright/index.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/preset/manager.ts
  src/preset/preview.ts
  src/typings.d.ts
  src/withGlobals.ts
  src/withRoundTrip.ts
  stories/Button.stories.js
  stories/basic/Button.js
  stories/basic/Button.stories.js
  stories/basic/Header.js
  stories/basic/Header.stories.js
  stories/basic/Page.js
  stories/basic/Page.stories.js
  stories/basic/button.css
  stories/basic/header.css
  stories/basic/page.css
  test-runner-jest.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement, patch

#25 fix: move test-runner default configuration location and resolution
  bin/test-storybook.js
  playwright/test-runner-jest.config.js
  test-runner-jest.config.js
Labels: patch

#27 Update ci recipes and timeout feedback
  README.md
  playwright/custom-environment.js
Labels: patch

#29 docs(README): add section about jest
  README.md
Labels: documentation, skip-release

#31 Add stories.json support
  .storybook/main.js
  .vscode/settings.json
  README.md
  bin/test-storybook.js
  package.json
  playwright/test-runner-jest.config.js
  src/csf/transformCsf.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  stories/basic/Introduction.stories.mdx
  stories/basic/assets/code-brackets.svg
  stories/basic/assets/colors.svg
  stories/basic/assets/comments.svg
  stories/basic/assets/direction.svg
  stories/basic/assets/flow.svg
  stories/basic/assets/plugin.svg
  stories/basic/assets/repo.svg
  stories/basic/assets/stackalt.svg
  test-runner-jest.config.js
  yarn.lock
Labels: enhancement
