Repository storybookjs/test-runner, pull requests merged in 2022-03, with the labels that each got.

#67 cleanup jsdom related code
  LICENSE
  jsdom-jest.config.js
  jsdom/transform.js
  mocks/fileMock.js
  mocks/htmlMock.js
  mocks/styleMock.js
  package.json
  preset.js
  src/jsdom/index.ts
  src/jsdom/transformJsdom.test.ts
  src/jsdom/transformJsdom.ts
Labels: maintenance

#72 Cleanup dependencies
  package.json
  yarn.lock
Labels: dependencies

#79 Add ability to test docs pages via VIEW_MODE env var
  .storybook/test-runner.ts
  src/setup-page.ts
Labels: enhancement
