Repository storybookjs/test-runner, pull requests merged in 2022-09, with the labels that each got.

#186 docs(README): Update a11y recipe
  README.md
Labels: documentation, skip-release

#188 Release 0.7.1
  README.md
  package.json
  yarn.lock
Labels: patch

#189 Regenerate yarn.lock [skip ci]
  yarn.lock
Labels: skip-release

#192 fix snapshots & remove vscode color settings
  .vscode/settings.json
  __snapshots__/atoms-button--demo.png
  __snapshots__/atoms-button--find-by.png
  __snapshots__/atoms-button--primary.png
  __snapshots__/atoms-button--wait-for-element-to-be-removed.png
  __snapshots__/atoms-button--wait-for.png
  __snapshots__/atoms-button--with-loaders.png
  __snapshots__/molecules-header--logged-in.png
  __snapshots__/molecules-header--logged-out.png
  __snapshots__/pages-page--logged-in.png
  __snapshots__/pages-page--logged-out.png
Labels: skip-release, maintenance

#190 Support Storybook 7.0 play function exceptions
  __snapshots__/atoms-button--demo-snap.png
  __snapshots__/atoms-button--find-by-snap.png
  __snapshots__/atoms-button--primary-snap.png
  __snapshots__/atoms-button--wait-for-element-to-be-removed-snap.png
  __snapshots__/atoms-button--wait-for-snap.png
  __snapshots__/atoms-button--with-loaders-snap.png
  __snapshots__/molecules-header--logged-in-snap.png
  __snapshots__/molecules-header--logged-out-snap.png
  __snapshots__/pages-page--logged-in-snap.png
  __snapshots__/pages-page--logged-out-snap.png
  src/setup-page.ts
Labels: patch
