Repository storybookjs/test-runner, pull requests merged in 2022-10, with the labels that each got.

#198 Add isTestRunner utility
  .storybook/is-test-runner.js
  .storybook/preview.js
  README.md
  bin/test-storybook.js
  package.json
  src/setup-page.ts
  stories/atoms/Button.stories.js
Labels: minor

#194 Fix StorybookTestRunnerError – length on undefined
  src/setup-page.ts
Labels: patch

#199 Release 0.8.0
  .storybook/is-test-runner.js
  .storybook/preview.js
  README.md
  bin/test-storybook.js
  package.json
  src/setup-page.ts
  stories/atoms/Button.stories.js
Labels: minor

#201 Improve error logging and ensure non-zero exit
  bin/test-storybook.js
Labels: patch

#197 Fix nightly check for failures
  .github/workflows/nightly.yml
Labels: skip-release

#202 Upgrade preset-env to latest
  package.json
  yarn.lock
Labels: patch

#205 Docs: update coverage section now that the addon supports Vite
  README.md
Labels: documentation, skip-release

#204 feat: add cli option --ci
  README.md
  src/util/getParsedCliOptions.ts
Labels: minor

#206 Release 0.9.0
  .github/workflows/nightly.yml
  README.md
  bin/test-storybook.js
  package.json
  src/util/getParsedCliOptions.ts
  yarn.lock
Labels: minor

#210 New prerelease structure / upgrade to SB7
  .storybook/main.js
  README.md
  package.json
  src/csf/transformCsf.ts
  src/playwright/transformPlaywright.ts
  src/util/getStorybookMetadata.test.ts
  stories/docs/Introduction.stories.mdx
  yarn.lock
Labels: minor

#213 Upgrade nightly to next instead of future
  .github/workflows/nightly.yml
Labels: skip-release
