Repository storybookjs/test-runner, pull requests merged in 2022-02, with the labels that each got.

#41 Add CLI wrapper
  README.md
  bin/test-storybook.js
  package.json
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/util/cli.test.ts
  src/util/cli.ts
  src/util/helpers.ts
  yarn.lock
Labels: enhancement

#38 Add setPreRender/setPostRender hooks & example
  README.md
  __snapshots__/basic-button--demo-snap.png
  __snapshots__/basic-button--find-by-snap.png
  __snapshots__/basic-button--primary-snap.png
  __snapshots__/basic-button--wait-for-element-to-be-removed-snap.png
  __snapshots__/basic-button--wait-for-snap.png
  __snapshots__/basic-button--with-loaders-snap.png
  __snapshots__/example-header--logged-in-snap.png
  __snapshots__/example-header--logged-out-snap.png
  __snapshots__/example-page--logged-in-snap.png
  __snapshots__/example-page--logged-out-snap.png
  jest-setup.js
  package.json
  src/csf/transformCsf.ts
  src/index.ts
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/typings.d.ts
  test-runner-jest.config.js
  yarn.lock
Labels: enhancement

#43 Test runner version 0.0.2
  .github/workflows/linear-export.yml
  .github/workflows/stress-test.yml
  .github/workflows/test.yml
  .gitignore
  .storybook/main.js
  .vscode/settings.json
  README.md
  __snapshots__/basic-button--demo-snap.png
  __snapshots__/basic-button--find-by-snap.png
  __snapshots__/basic-button--primary-snap.png
  __snapshots__/basic-button--wait-for-element-to-be-removed-snap.png
  __snapshots__/basic-button--wait-for-snap.png
  __snapshots__/basic-button--with-loaders-snap.png
  __snapshots__/example-header--logged-in-snap.png
  __snapshots__/example-header--logged-out-snap.png
  __snapshots__/example-page--logged-in-snap.png
  __snapshots__/example-page--logged-out-snap.png
  bin/test-storybook.js
  jest-setup.js
  package.json
  playwright/custom-environment.js
  playwright/test-runner-jest.config.js
  playwright/transform.js
  scripts/generate-dynamic-stories.js
  src/csf/transformCsf.ts
  src/index.ts
  src/jsdom/transformJsdom.ts
  src/playwright/hooks.ts
  src/playwright/index.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  src/typings.d.ts
  src/util/cli.test.ts
  src/util/cli.ts
  src/util/helpers.ts
  stories/basic/Button.stories.js
  stories/basic/Introduction.stories.mdx
  stories/basic/assets/code-brackets.svg
  stories/basic/assets/colors.svg
  stories/basic/assets/comments.svg
  stories/basic/assets/direction.svg
  stories/basic/assets/flow.svg
  stories/basic/assets/plugin.svg
  stories/basic/assets/repo.svg
  stories/basic/assets/stackalt.svg
  test-runner-jest.config.js
  yarn.lock
Labels: patch

#51 fix: improve error message in start-storybook
  bin/test-storybook.js
Labels: patch

#52 feat: add update snapshot command to cli
  README.md
  src/util/getParsedCliOptions.ts
Labels: patch

#53 Test-runner file for hook configuration
  .storybook/test-runner.ts
  README.md
  jest-setup.js
  playwright/jest-setup.js
  src/config/jest-playwright.ts
  src/index.ts
  src/playwright/hooks.ts
  src/util/getTestRunnerConfig.ts
  src/util/index.ts
  test-runner-jest.config.js
Labels: enhancement, patch

#54 feat: add eject command
  README.md
  bin/test-storybook.js
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  test-runner-jest.config.js
Labels: enhancement, patch

#57 fix: add file location to eject error message
  bin/test-storybook.js
Labels: patch

#55 feat: add browsers flag
  README.md
  bin/test-storybook.js
  src/config/jest-playwright.ts
  src/util/getCliOptions.test.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
Labels: enhancement, linear, patch

#56 feat: add url flag
  README.md
  bin/test-storybook.js
  playwright/custom-environment.js
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
Labels: enhancement, linear, patch

#58 feat: add url flag
  README.md
  bin/test-storybook.js
  playwright/custom-environment.js
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
Labels: patch

#60 feat: auto detect stories json mode
  README.md
  bin/test-storybook.js
  package.json
  src/util/getParsedCliOptions.ts
  yarn.lock
Labels: enhancement, linear, patch

#61 feat: add typeahead jest plugin
  package.json
  src/config/jest-playwright.ts
  yarn.lock
Labels: enhancement, linear, patch

#65 fix: use correct import in generated test
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  test-runner-jest.config.js
Labels: patch

#66 Release 0.0.4
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  test-runner-jest.config.js
Labels: patch
