Repository storybookjs/test-runner, pull requests merged in 2022-05, with the labels that each got.

#107 fix: Support Storybook 6.5
  package.json
  src/csf/transformCsf.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  yarn.lock
Labels: bug, minor

#108 Release 0.1.0
  package.json
  src/csf/transformCsf.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  yarn.lock
Labels: minor

#105 Document issue with Jest on Windows CI
  README.md
Labels: documentation

#111 Add Jest compatibility check
  .vscode/settings.json
  README.md
  bin/test-storybook.js
  package.json
  yarn.lock
Labels: patch

#112 Release 0.1.1
  .vscode/settings.json
  README.md
  bin/test-storybook.js
  package.json
  yarn.lock
Labels: patch

#113 Add reporting to CI
  .github/workflows/nightly.yml
  .storybook/main.js
Labels: skip-release

#115 Updates readme to lock Jest to version 27
  README.md
Labels: documentation, skip-release
