Repository storybookjs/test-runner, pull requests merged in 2022-08, with the labels that each got.

#154 feat: jest 28 support
  README.md
  bin/test-storybook.js
  package.json
  playwright/transform.js
  yarn.lock
Labels: minor

#157 feat: add console logs on test failure
  src/setup-page.ts
Labels: enhancement, minor

#162 use storybook@future on nightly script
  .github/workflows/nightly.yml
Labels: skip-release, maintenance

#164 Update stories in example Storybook
  __snapshots__/pages-page--logged-in-snap.png
  __snapshots__/pages-page--logged-out-snap.png
  stories/atoms/Button.jsx
  stories/molecules/Header.jsx
  stories/molecules/Header.stories.jsx
  stories/molecules/__snapshots__/Header.stories.jsx.snap
  stories/molecules/header.css
  stories/pages/Page.js
  stories/pages/Page.jsx
  stories/pages/Page.stories.js
  stories/pages/Page.stories.jsx
  stories/pages/__snapshots__/Page.stories.jsx.snap
  stories/pages/page.css
Labels: skip-release

#166 feat: throw error on unconfigured coverage when running with --coverage
  src/setup-page.ts
Labels: patch

#168 fix --watch cli option
  src/util/getParsedCliOptions.ts
Labels: patch

#169 undo Jest 28 support
  README.md
  bin/test-storybook.js
  package.json
  playwright/transform.js
  yarn.lock
Labels: patch

#170 Add commit hooks
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests.yml
  .husky/pre-commit
  .prettierignore
  .storybook/main.js
  .vscode/settings.json
  README.md
  package.json
  playwright/custom-environment.js
  playwright/jest-setup.js
  playwright/test-runner-jest.config.js
  playwright/transform.js
  stories/atoms/Button.jsx
  stories/atoms/Button.stories.js
  stories/expected-failures/Failure.stories.jsx
  test-runner-jest.config.js
  tsconfig.json
  yarn.lock
Labels: skip-release, maintenance

#171 Release 0.6.0
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  .storybook/main.js
  .storybook/test-runner.ts
  .vscode/settings.json
  README.md
  __snapshots__/pages-page--logged-in-snap.png
  __snapshots__/pages-page--logged-out-snap.png
  bin/test-storybook.js
  package.json
  playwright/custom-environment.js
  playwright/jest-setup.js
  playwright/test-runner-jest.config.js
  playwright/transform.js
  src/setup-page.ts
  src/util/getParsedCliOptions.ts
  stories/atoms/Button.jsx
  stories/atoms/Button.stories.js
  stories/expected-failures/Failure.stories.jsx
  stories/molecules/Header.jsx
  stories/molecules/Header.stories.jsx
  stories/molecules/__snapshots__/Header.stories.jsx.snap
  stories/molecules/header.css
  stories/pages/Page.js
  stories/pages/Page.jsx
  stories/pages/Page.stories.js
  stories/pages/Page.stories.jsx
  stories/pages/__snapshots__/Page.stories.jsx.snap
  stories/pages/page.css
  test-runner-jest.config.js
  tsconfig.json
  yarn.lock
Labels: minor

#172 support Storybook 7.0 root selector
  .storybook/test-runner.ts
  README.md
  src/setup-page.ts
Labels: patch

#173 Release 0.6.1
  .storybook/test-runner.ts
  README.md
  src/setup-page.ts
Labels: patch

#175 feat: turn Jest into an internal dependency
  README.md
  bin/test-storybook.js
  package.json
  yarn.lock
Labels: patch

#176 Release 0.6.2
  README.md
  bin/test-storybook.js
  package.json
  yarn.lock
Labels: patch

#177 Support storyStoreV7 in coverage check
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
Labels: patch

#178 Release 0.6.3
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
Labels: patch

#180 Add remark regarding different coverage providers
  README.md
Labels: documentation, skip-release

#179 add --junit flag to test runner
  .gitignore
  README.md
  bin/test-storybook.js
  package.json
  src/config/jest-playwright.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  yarn.lock
Labels: patch

#181 Release 0.6.4
  .gitignore
  README.md
  bin/test-storybook.js
  package.json
  src/config/jest-playwright.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  yarn.lock
Labels: patch

#174 Update Jest to 28
  README.md
  bin/test-storybook.js
  package.json
  playwright/transform.js
  src/config/jest-playwright.ts
  yarn.lock
Labels: minor

#182 Release 0.7.0
  README.md
  bin/test-storybook.js
  package.json
  playwright/transform.js
  src/config/jest-playwright.ts
  yarn.lock
Labels: minor
