Repository storybookjs/test-runner, pull requests merged in 2023-06, with the labels that each got.

#303 fix: Remove last reference to regenerator-runtime
  playwright/custom-environment.js
Labels: patch, pick

#297 Improve ejected config types
  playwright/test-runner-jest.config.js
Labels: patch

#257 fix: nyc command with shard option
  README.md
  src/test-storybook.ts
Labels: patch, pick

#315 Change dependencies from `future` npm tag to `next`
  package.json
  yarn.lock
Labels: patch

#318 Release 0.11.0
  .github/ISSUE_TEMPLATE/bug-report-🐞.md
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/test-runner.ts
  README.md
  package.json
  playwright/custom-environment.js
  playwright/jest-setup.js
  playwright/test-runner-jest.config.js
  playwright/transform.js
  src/config/jest-playwright.ts
  src/csf/transformCsf.ts
  src/playwright/hooks.ts
  src/playwright/index.ts
  src/playwright/transformPlaywrightJson.ts
  src/test-storybook.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  stories/docs/Introduction.mdx
  test-runner-jest.config.js
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: minor

#320 docs: fix github actions example for shard usage
  README.md
Labels: skip-release
