Repository storybookjs/test-runner, pull requests merged in 2023-10, with the labels that each got.

#349 deps/devDeps: bump semver to latest [CVE-2022-25883]
  package.json
  yarn.lock
Labels: patch

#363 Docs: Expand ejected config docs with an example
  README.md
Labels: documentation, skip-release

#364 Run nyc with correct packager manager command
  .github/ISSUE_TEMPLATE/bug-report-🐞.md
  .storybook/main.ts
  package.json
  src/test-storybook.ts
  yarn.lock
Labels: patch

#361 Add waitForPageReady utility
  .storybook/test-runner.ts
  README.md
  src/playwright/hooks.ts
Labels: minor

#373 Documentation: restructure docs and include more recipes
  README.md
Labels: skip-release

#354 BREAKING: Bump minimum Node.js version to ^14.15.0
  package.json
Labels: minor

#348 BREAKING: Upgrade Jest to v29
  README.md
  package.json
  src/playwright/transformPlaywrightJson.test.ts
  src/util/__snapshots__/getStorybookMain.test.ts.snap
  yarn.lock
Labels: minor, dependencies
