Repository storybookjs/test-runner, pull requests merged in 2023-04, with the labels that each got.

#288 Bump @storybook/csf to 0.1.0
  package.json
  yarn.lock
Labels: patch

#289 Support Storybook 7.0.0
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .storybook/is-test-runner.ts
  .storybook/main.js
  README.md
  bin/test-storybook.js
  package.json
  playwright/custom-environment.js
  playwright/jest-setup.js
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
  src/util/__snapshots__/getStorybookMain.test.ts.snap
  src/util/getStorybookMain.test.ts
  src/util/getStorybookMain.ts
  src/util/getStorybookMetadata.test.ts
  src/util/getTestRunnerConfig.ts
  stories/docs/Introduction.stories.mdx
  yarn.lock
Labels: minor

#290 upgrade example storybook [skip ci]
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  stories/docs/Introduction.mdx
  yarn.lock
Labels: skip-release

#250 Bundle with tsup and replace babel-jest
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .storybook/test-runner.ts
  package.json
  playwright/custom-environment.js
  playwright/jest-setup.js
  playwright/transform.js
  src/config/jest-playwright.ts
  src/csf/transformCsf.ts
  src/playwright/hooks.ts
  src/playwright/index.ts
  src/playwright/transformPlaywrightJson.ts
  src/test-storybook.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  test-runner-jest.config.js
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: minor, maintenance

#299 Upgrade glob to v10
  package.json
  src/test-storybook.ts
  yarn.lock
Labels: patch
