Repository storybookjs/test-runner, pull requests merged in 2023-11, with the labels that each got.

#377 Release 0.14.0
  .github/ISSUE_TEMPLATE/bug-report-🐞.md
  .github/workflows/nightly.yml
  .gitignore
  .storybook/main.ts
  .storybook/test-runner.ts
  .yarn/releases/yarn-3.6.3.cjs
  .yarnrc.yml
  README.md
  package.json
  playwright/test-runner-jest.config.js
  src/config/jest-playwright.ts
  src/playwright/hooks.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/util/__snapshots__/getStorybookMain.test.ts.snap
  test-runner-jest.config.js
  yarn.lock
Labels: minor

#387 Fix: Do not set test root outside index json mode
  README.md
  src/test-storybook.ts
Labels: patch

#388 Release 0.14.1
  README.md
  src/test-storybook.ts
Labels: patch

#380 Add storyshots migration guides
  MIGRATION.md
  MIGRATION.portable-stories.md
  MIGRATION.test-runner.md
Labels: skip-release

#389 Chore: update wait-on and lockfile
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  README.md
  package.json
  src/util/getStorybookMetadata.test.ts
  yarn.lock
Labels: patch

#385 fix: switch `checkStorybook` to use `GET` method
  src/test-storybook.ts
Labels: bug

#382 Add support for test filtering via tags
  .storybook/test-runner.ts
  README.md
  package.json
  src/csf/transformCsf.ts
  src/playwright/hooks.ts
  src/playwright/index.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  src/util/getTagOptions.ts
  yarn.lock
Labels: feature request, minor

#390 Release 0.15.0
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .storybook/test-runner.ts
  MIGRATION.md
  MIGRATION.portable-stories.md
  MIGRATION.test-runner.md
  README.md
  package.json
  src/csf/transformCsf.ts
  src/playwright/hooks.ts
  src/playwright/index.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.ts
  src/util/getStorybookMetadata.test.ts
  src/util/getTagOptions.ts
  yarn.lock
Labels: minor

#391 fix: Make tags optional in TestRunnerConfig
  src/playwright/hooks.ts
Labels: patch

#392 Release 0.15.1
  src/playwright/hooks.ts
Labels: patch

#393 Docs: Update tags documentation
  README.md
  src/playwright/hooks.ts
Labels: patch

#394 Refactor: Rename "render" hooks to "visit" hooks
  .storybook/test-runner.ts
  MIGRATION.test-runner.md
  README.md
  playwright/jest-setup.js
  playwright/test-runner-jest.config.js
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/test-storybook.ts
  src/typings.d.ts
Labels: patch

#396 Clarify difference between skipped and excluded tags
  README.md
Labels: skip-release

#397 Fix "Browser has been closed" crash on uncaught page errors
  playwright/jest-setup.js
  src/config/jest-playwright.ts
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
Labels: patch

#398 Docs: Add react native remark to troubleshooting section
  README.md
Labels: skip-release

#353 Remove Node 14 from engines field
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .nvmrc
  .storybook/main.ts
  package.json
Labels: patch

#399 Release 0.15.2
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-extended.yml
  .github/workflows/tests.yml
  .nvmrc
  .storybook/main.ts
  .storybook/test-runner.ts
  MIGRATION.test-runner.md
  README.md
  package.json
  playwright/jest-setup.js
  playwright/test-runner-jest.config.js
  src/config/jest-playwright.ts
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/typings.d.ts
Labels: patch

#378 Refactor: Improve internal code
  .github/workflows/tests.yml
  .github/workflows/typecheck.yml
  jest.config.js
  src/config/jest-playwright.test.ts
  src/config/jest-playwright.ts
  src/csf/__snapshots__/transformCsf.test.ts.snap
  src/csf/transformCsf.test.ts
  src/csf/transformCsf.ts
  src/playwright/hooks.test.ts
  src/playwright/transformPlaywright.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/util/__snapshots__/getStorybookMain.test.ts.snap
  src/util/getCliOptions.test.ts
  src/util/getCliOptions.ts
  src/util/getParsedCliOptions.test.ts
  src/util/getParsedCliOptions.ts
  src/util/getStorybookMain.ts
  src/util/getStorybookMetadata.ts
  src/util/getTestRunnerConfig.test.ts
  src/util/getTestRunnerConfig.ts
  tsconfig.json
  tsup.config.ts
Labels: patch

#400 Bump `jest-playwright-preset` from `v3.0.1` to `v4.0.0`
  package.json
  yarn.lock
Labels: patch

#402 Docs: Adds feedback form to migration documentation
  MIGRATION.portable-stories.md
  MIGRATION.test-runner.md
Labels: skip-release

#404 Fix sync issues between tests
  playwright/jest-setup.js
  src/csf/__snapshots__/transformCsf.test.ts.snap
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page-script.ts
  src/setup-page.ts
Labels: patch

#405 Filter duplicated error messages in browser logs
  src/setup-page-script.ts
Labels: patch

#406 Introduce logLevel configuration
  .storybook/test-runner.ts
  README.md
  src/playwright/hooks.ts
  src/setup-page-script.ts
  src/setup-page.ts
Labels: feature request, minor
