Repository storybookjs/test-runner, pull requests merged in 2023-09, with the labels that each got.

#347 chore: dedupe dependency versions in `yarn.lock`
  yarn.lock
Labels: skip-release, internal

#350 chore: disable yarn telemetry by default
  .yarnrc.yml
Labels: skip-release, internal

#351 chore: set `engines.node` to `>=12.0.0`
  package.json
Labels: bug, patch

#352 CI: Fix yarn 2 issue
  .github/workflows/nightly.yml
  package.json
  yarn.lock
Labels: skip-release

#346 devDeps: Bump auto from v10 to v11
  package.json
  yarn.lock
Labels: skip-release
