Repository storybookjs/test-runner, pull requests merged in 2023-03, with the labels that each got.

#273 Use preview api instead of store
  package.json
  src/playwright/transformPlaywright.ts
  yarn.lock
Labels: patch, dependencies

#245 Extend hooks api with `prepare` and `getHttpHeaders` properties
  .storybook/main.js
  README.md
  bin/test-storybook.js
  playwright/custom-environment.js
  playwright/jest-setup.js
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/setup-page.ts
  src/util/getTestRunnerConfig.ts
Labels: feature request, patch, stress test

#278 Update getStorybookMain to throw an error if stories are not found in main.js
  src/util/__snapshots__/getStorybookMain.test.ts.snap
  src/util/getStorybookMain.test.ts
  src/util/getStorybookMain.ts
Labels: bug, patch

#283 support Storybook 7.0.0
  package.json
  yarn.lock
Labels: patch
