Repository storybookjs/test-runner, pull requests merged in 2024-06, with the labels that each got.

#481 Unpin @swc/core from 1.5.7
  package.json
  yarn.lock
Labels: patch

#483 Fix contents of eject functionality
  src/test-storybook.ts
Labels: patch

#485 Fix: Combine tags correctly when transforming story files
  .storybook/preview.ts
  README.md
  src/csf/transformCsf.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  src/test-storybook.ts
  src/util/getTagOptions.ts
Labels: bug, patch

#468 Feat: Add errorMessageFormatter
  .storybook/test-runner.ts
  README.md
  src/playwright/hooks.ts
  src/setup-page-script.ts
  src/setup-page.ts
  yarn.lock
Labels: feature request, minor

#486 Release 0.19.0
  .storybook/preview.ts
  .storybook/test-runner.ts
  README.md
  package.json
  src/csf/transformCsf.ts
  src/playwright/hooks.ts
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
  src/playwright/transformPlaywrightJson.ts
  src/setup-page-script.ts
  src/setup-page.ts
  src/test-storybook.ts
  src/util/getTagOptions.ts
  yarn.lock
Labels: feature request, minor
