Repository storybookjs/test-runner, pull requests merged in 2024-12, with the labels that each got.

#519 Fix postVisit hook issue
  src/csf/__snapshots__/transformCsf.test.ts.snap
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
Labels: patch

#520 Release 0.20.1
  src/csf/__snapshots__/transformCsf.test.ts.snap
  src/playwright/transformPlaywright.test.ts
  src/playwright/transformPlaywright.ts
  src/playwright/transformPlaywrightJson.test.ts
Labels: patch

#521 Feature: Add --listTests flag from Jest
  README.md
  src/util/getParsedCliOptions.ts
Labels: minor

#526 Fix: Handle RSC errors
  src/setup-page-script.ts
Labels: patch

#523 style(README): highlight Markdown Note section
  README.md
Labels: skip-release

#527 Release 0.21.0
  README.md
  src/setup-page-script.ts
  src/util/getParsedCliOptions.ts
Labels: minor
