Repository storybookjs/test-runner, pull requests merged in 2024-05, with the labels that each got.

#456 Fix coverage reports, add lcov as extra reporter
  package.json
  src/test-storybook.ts
  yarn.lock
Labels: minor

#409 add `--testTimeout` cli option from jest
  README.md
  src/util/getParsedCliOptions.ts
Labels: patch

#458 Release 0.18.0
  .github/ISSUE_TEMPLATE/bug-report-🐞.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  package.json
  src/test-storybook.ts
  src/util/getParsedCliOptions.ts
  yarn.lock
Labels: minor

#464 Fix: Skip requiring a main.js file in index.json mode
  package.json
  src/test-storybook.ts
  yarn.lock
Labels: patch

#462 Fix getStoryContext type
  src/playwright/hooks.ts
Labels: patch

#461 Fix Windows support in coverage generation
  src/test-storybook.ts
Labels: patch

#466 Release 0.18.1
  package.json
  src/playwright/hooks.ts
  src/test-storybook.ts
  yarn.lock
Labels: patch

#474 Pin `@swc/core` to 1.5.7
  package.json
  yarn.lock
Labels: patch, dependencies

#475 Fix 8.1.4+ support for v5 index.json
  src/playwright/transformPlaywrightJson.ts
Labels: bug, patch

#476 Release 0.18.2
  package.json
  src/playwright/transformPlaywrightJson.ts
  yarn.lock
Labels: patch
