Repository storybookjs/test-runner, pull requests merged in 2024-01, with the labels that each got.

#423 Remove --prerelease from sb upgrade CI
  .github/workflows/nightly.yml
Labels: skip-release, maintenance

#425 Fix build step
  src/csf/transformCsf.ts
  src/playwright/transformPlaywrightJson.ts
Labels: skip-release

#428 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-release

#427 swap storybook/jest to storybook/test
  package.json
  stories/atoms/Button.stories.tsx
  stories/expected-failures/Failure.stories.tsx
  stories/pages/Page.stories.tsx
  yarn.lock
Labels: skip-release, maintenance

#421 Support unhandled rendering errors
  src/setup-page-script.ts
Labels: patch

#429 Support Storybook 8
  package.json
  yarn.lock
Labels: minor

#430 Update internal example to Storybook 8
  package.json
  stories/atoms/Button.stories.tsx
  stories/expected-failures/Failure.stories.tsx
  yarn.lock
Labels: skip-release

#431 Prebundle dependencies
  .storybook/test-runner.ts
  package.json
  playwright/custom-environment.js
  playwright/test-runner-jest.config.js
  playwright/transform.js
  src/config/jest-playwright.ts
  src/index.ts
  src/setup-page.ts
  tsup.config.ts
  yarn.lock
Labels: patch

#432 Docs: Add remark regarding pnp support
  README.md
Labels: documentation, skip-release
