Repository storybookjs/test-runner, pull requests merged in 2025-02, with the labels that each got.

#536 Fix a11y compatibility with Storybook 8.5 and above
  src/setup-page-script.ts
Labels: patch

#544 Promote v0.21.1-next.0
  src/setup-page-script.ts
Labels: bug, patch

#546 Revert "Fix a11y compatibility with Storybook 8.5 and above"
  src/setup-page-script.ts
Labels: minor

#547 Release 0.21.2 patch
  src/setup-page-script.ts
Labels: patch

#548 fix: Use StoryFinished event if available
  src/setup-page.ts
Labels: patch

#549 Release 0.21.3
  src/setup-page.ts
Labels: patch

#551 Dependencies: Add sb9 alpha compatibility
  package.json
  yarn.lock
Labels: minor

#552 Exclude new server component error
  src/setup-page-script.ts
Labels: patch

#539 Fix --index-json flag not being honored for locally deployed storybooks
  src/test-storybook.ts
Labels: patch

#553 Release v0.22.0
  package.json
  src/setup-page-script.ts
  src/test-storybook.ts
  yarn.lock
Labels: minor
